---

image: "reporunner/golang-alpine"
checkout_dir: /go/src/github.com/Luzifer/wasm-openssl

commands:
  - make publish

environment:
  ARCHS: js/wasm
  CGO_ENABLED: 0
  DRAFT: "false"
  NO_TESTS: "true"
